# Generated by Django 6.0.1 on 2026-01-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_textanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='source',
            field=models.CharField(choices=[('manual', 'Вручну'), ('auto', 'Аналізатор')], default='manual', max_length=10),
        ),
    ]
