# Generated by Django 6.0.1 on 2026-01-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_word_is_learned_word_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textanalysis',
            old_name='original_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='textanalysis',
            name='word_frequency_json',
        ),
        migrations.AddField(
            model_name='textanalysis',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='analyses', to='vocabulary.word'),
        ),
        migrations.AlterField(
            model_name='textanalysis',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
