# Generated by Django 6.0.1 on 2026-01-31 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_rename_original_text_textanalysis_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=1)),
                ('translation', models.CharField(blank=True, max_length=255, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_vocabulary', to='vocabulary.textanalysis')),
            ],
            options={
                'ordering': ['-count'],
            },
        ),
    ]
