# Generated by Django 6.0.1 on 2026-02-01 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_textword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['is_learned', '-created_at']},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('english_level', models.CharField(choices=[('beginner', 'Beginner (A1)'), ('elementary', 'Elementary (A2)'), ('intermediate', 'Intermediate (B1)'), ('upper_intermediate', 'Upper Intermediate (B2)'), ('advanced', 'Advanced (C1)'), ('proficiency', 'Proficiency (C2)')], default='beginner', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
